baseURL = 'https://ibrahimmuftee.net/'
languageCode = 'en-us'
title = "Ibrahim's Website"
theme = "m10c"
paginate = 8

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3

[params]
  author = "Ibrahim Muftee"
  description = "A student and a musician that has nothing better to do."
  menu_item_separator = " - "
  [[params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com/abemuftee"
  [[params.social]]
    icon = "twitter"
    name = "Twitter"
    url = "https://twitter.com/abemuftee"
